development:
  port: 9312
  morphology: stem_en
  bin_path: "/usr/local/bin"
  configuration_file: "config/ENVIRONMENT.sphinx.conf"
  log: "log/searchd.log"
  query_log: "log/searchd.query.log"
  pid_file: "log/searchd.ENVIRONMENT.pid"
  searchd_file_path: "tmp/sphinx/development/"
test:
  port: 9315
  morphology: stem_en
  bin_path: "/usr/local/bin"
  configuration_file: "config/ENVIRONMENT.sphinx.conf"
  log: "log/searchd.log"
  query_log: "log/searchd.query.log"
  pid_file: "log/searchd.ENVIRONMENT.pid"
  searchd_file_path: "tmp/sphinx/test/"
  searchd_file_path: "tmp/sphinx/test/"
production:
  port: 9314
  morphology: stem_en
  bin_path: "/usr/local/sphinx/bin"
  log: "/srv/rails/mytravel-asia/shared/sphinx/searchd.log"
  query_log: "/srv/rails/mytravel-asia/shared/sphinx/searchd.query.log"
  pid_file: "/srv/rails/mytravel-asia/shared/sphinx/searchd.pid"
  searchd_file_path: "/srv/rails/mytravel-asia/shared/sphinx"
